package db

import (
	"context"
	"database/sql"

	_ "github.com/jackc/pgx/v5/stdlib"
)

type DB struct {
	*sql.DB
	*Queries // generated by sqlc; add your queries.sql and run sqlc
}

func Open(ctx context.Context, dsn string) (*DB, error) {
	sqldb, err := sql.Open("pgx", dsn)
	if err != nil {
		return nil, err
	}
	if err := sqldb.PingContext(ctx); err != nil {
		return nil, err
	}
	return &DB{
		DB:      sqldb,
		Queries: New(sqldb),
	}, nil
}
