// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Customer struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type CustomerToken struct {
	ID         int64        `json:"id"`
	CustomerID int64        `json:"customer_id"`
	Name       string       `json:"name"`
	TokenHash  string       `json:"token_hash"`
	CreatedAt  time.Time    `json:"created_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
}

type Invoice struct {
	ID            int64     `json:"id"`
	CustomerID    int64     `json:"customer_id"`
	PeriodStart   time.Time `json:"period_start"`
	PeriodEnd     time.Time `json:"period_end"`
	SubtotalCents int64     `json:"subtotal_cents"`
	DiscountCents int64     `json:"discount_cents"`
	TotalCents    int64     `json:"total_cents"`
	CreatedAt     time.Time `json:"created_at"`
}

type InvoiceLineItem struct {
	ID             int64     `json:"id"`
	InvoiceID      int64     `json:"invoice_id"`
	ServiceID      int64     `json:"service_id"`
	WindowStart    time.Time `json:"window_start"`
	WindowEnd      time.Time `json:"window_end"`
	PrimaryBytes   int64     `json:"primary_bytes"`
	BackupBytes    int64     `json:"backup_bytes"`
	CoverageFactor float64   `json:"coverage_factor"`
	AmountCents    int64     `json:"amount_cents"`
	DiscountCents  int64     `json:"discount_cents"`
	CreatedAt      time.Time `json:"created_at"`
}

type Service struct {
	ID         int64        `json:"id"`
	CustomerID int64        `json:"customer_id"`
	Name       string       `json:"name"`
	PrimaryCdn string       `json:"primary_cdn"`
	BackupCdn  string       `json:"backup_cdn"`
	CreatedAt  time.Time    `json:"created_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
}

type ServiceDomain struct {
	ID        int64     `json:"id"`
	ServiceID int64     `json:"service_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type StormEvent struct {
	ID        int64        `json:"id"`
	ServiceID int64        `json:"service_id"`
	Kind      string       `json:"kind"`
	StartedAt time.Time    `json:"started_at"`
	EndedAt   sql.NullTime `json:"ended_at"`
}

type StormPolicy struct {
	ID                int64     `json:"id"`
	ServiceID         int64     `json:"service_id"`
	Kind              string    `json:"kind"`
	ThresholdAvail    float64   `json:"threshold_avail"`
	WindowSeconds     int32     `json:"window_seconds"`
	CooldownSeconds   int32     `json:"cooldown_seconds"`
	MaxCoverageFactor float64   `json:"max_coverage_factor"`
	CreatedAt         time.Time `json:"created_at"`
}

type UsageSnapshot struct {
	ID           int64         `json:"id"`
	ServiceID    int64         `json:"service_id"`
	WindowStart  time.Time     `json:"window_start"`
	WindowEnd    time.Time     `json:"window_end"`
	PrimaryBytes int64         `json:"primary_bytes"`
	BackupBytes  int64         `json:"backup_bytes"`
	CreatedAt    time.Time     `json:"created_at"`
	InvoiceID    sql.NullInt64 `json:"invoice_id"`
}
